Repository yml-org/fe-component-library, pull requests merged in 2023-02, with the labels that each got.

#20 feat(changelog): add changelog for release
  CHANGELOG.md
  package.json
Labels: documentation

#23 feat(storybook): update documentation for header component
  packages/header/src/header/header.component.stories.mdx
  packages/header/src/header/header.component.ts
  packages/video/src/video/video.component.ts
Labels: documentation

#24 feat(storybook): improve documentation
  packages/button/src/button/button.component.stories.mdx
  packages/image/src/image/image.component.stories.mdx
  packages/link/src/link/link.component.stories.mdx
Labels: documentation

#25 feat(storybook): improve documentation for video component
  CHANGELOG.md
  package.json
  packages/video/src/video/video.component.stories.mdx
Labels: documentation

#28 HOTFIX: Fix hamburger menu icon for header component
  CHANGELOG.md
  README.md
  package.json
  packages/header/src/header/header.component.ts
Labels: bug, hotfix

#30 CM/1138 : flick-to-transition component
  packages/page-transition/.idea/.gitignore
  packages/page-transition/.idea/TSK.iml
  packages/page-transition/.idea/modules.xml
  packages/page-transition/.idea/vcs.xml
  packages/page-transition/LICENSE
  packages/page-transition/README.md
  packages/page-transition/index.html
  packages/page-transition/package.json
  packages/page-transition/pnpm-lock.yaml
  packages/page-transition/src/constants/transition.component.ts
  packages/page-transition/src/shared/globals.d.ts
  packages/page-transition/src/shared/tailwind.element.ts
  packages/page-transition/src/shared/tailwind.global.css
  packages/page-transition/src/transition/transition.component.scss
  packages/page-transition/src/transition/transition.component.stories.mdx
  packages/page-transition/src/transition/transition.component.ts
  packages/page-transition/tailwind.config.js
  packages/page-transition/tsconfig.json
  packages/page-transition/vite.config.js
  packages/page-transition/yarn.lock
  yarn.lock
Labels: feature

#32 Added Documentation and unit test cases
  jest.config.js
  packages/page-transition/README.md
  packages/page-transition/dist/assets/index.0720e34e.css
  packages/page-transition/dist/assets/index.js
  packages/page-transition/dist/index.html
  packages/page-transition/src/transition/__snapshots__/transition.component.spec.ts.snap
  packages/page-transition/src/transition/transition.component.spec.ts
  packages/page-transition/src/transition/transition.component.stories.mdx
Labels: documentation, test cases

#34 Feature: Avatar Component
  .storybook/main.js
  jest.config.js
  package.json
  packages/avatar/.gitignore
  packages/avatar/LICENSE
  packages/avatar/README.md
  packages/avatar/index.html
  packages/avatar/lit-localize.json
  packages/avatar/package.json
  packages/avatar/src/avatar/__snapshots__/avatar.component.spec.ts.snap
  packages/avatar/src/avatar/avatar.component.scss
  packages/avatar/src/avatar/avatar.component.spec.ts
  packages/avatar/src/avatar/avatar.component.stories.mdx
  packages/avatar/src/avatar/avatar.component.ts
  packages/avatar/src/constants/avatar.variants.ts
  packages/avatar/src/shared/globals.d.ts
  packages/avatar/src/shared/tailwind.element.ts
  packages/avatar/src/shared/tailwind.global.css
  packages/avatar/src/types/avatar.ts
  packages/avatar/tailwind.config.js
  packages/avatar/tsconfig.json
  packages/avatar/vite.config.js
  packages/avatar/xliff/es-419.xlf
  packages/avatar/xliff/zh-Hans.xlf
  packages/page-transition/.gitignore
  yarn.lock
Labels: feature

#36 Feature/card component
  jest.config.js
  packages/card/.gitignore
  packages/card/LICENSE
  packages/card/README.md
  packages/card/index.html
  packages/card/lit-localize.json
  packages/card/package.json
  packages/card/src/card/__snapshots__/card.component.spec.ts.snap
  packages/card/src/card/card.component.scss
  packages/card/src/card/card.component.spec.ts
  packages/card/src/card/card.component.stories.mdx
  packages/card/src/card/card.component.ts
  packages/card/src/constants/card.ts
  packages/card/src/constants/card.variants.ts
  packages/card/src/shared/globals.d.ts
  packages/card/src/shared/tailwind.element.ts
  packages/card/src/shared/tailwind.global.css
  packages/card/src/types/card.ts
  packages/card/tailwind.config.js
  packages/card/tsconfig.json
  packages/card/vite.config.js
Labels: feature

#37 Feature: Textarea component
  .storybook/manager.js
  jest.config.js
  packages/list/src/constants/list.variants.ts
  packages/list/src/list/list.component.stories.mdx
  packages/list/src/list/list.component.ts
  packages/list/src/types/list.ts
  packages/text-area/.gitignore
  packages/text-area/LICENSE
  packages/text-area/README.md
  packages/text-area/index.html
  packages/text-area/lit-localize.json
  packages/text-area/package.json
  packages/text-area/src/constants/text-area.ts
  packages/text-area/src/constants/text-area.variants.ts
  packages/text-area/src/shared/globals.d.ts
  packages/text-area/src/shared/tailwind.element.ts
  packages/text-area/src/shared/tailwind.global.css
  packages/text-area/src/text-area/__snapshots__/textArea.component.spec.ts.snap
  packages/text-area/src/text-area/textArea.component.spec.ts
  packages/text-area/src/text-area/textArea.component.stories.scss
  packages/text-area/src/text-area/textArea.component.ts
  packages/text-area/src/text-area/textArea.stories.mdx
  packages/text-area/src/types/text-area.ts
  packages/text-area/tailwind.config.js
  packages/text-area/tsconfig.json
  packages/text-area/vite.config.js
Labels: feature

#39 Feature/CM-1184 Scroll Transition Component
  packages/scroll-component/.idea/.gitignore
  packages/scroll-component/.idea/TSK.iml
  packages/scroll-component/.idea/modules.xml
  packages/scroll-component/.idea/vcs.xml
  packages/scroll-component/LICENSE
  packages/scroll-component/README.md
  packages/scroll-component/index.html
  packages/scroll-component/package.json
  packages/scroll-component/pnpm-lock.yaml
  packages/scroll-component/src/assets/yonder/images/desktop/png/yonder-0001.png
  packages/scroll-component/src/assets/yonder/images/desktop/png/yonder-0002.png
  packages/scroll-component/src/assets/yonder/images/desktop/png/yonder-0003.png
  packages/scroll-component/src/assets/yonder/images/desktop/png/yonder-0004.png
  packages/scroll-component/src/assets/yonder/images/desktop/png/yonder-0005.png
  packages/scroll-component/src/assets/yonder/images/mobile/png/yonder-0001.png
  packages/scroll-component/src/assets/yonder/images/mobile/png/yonder-0002.png
  packages/scroll-component/src/assets/yonder/images/mobile/png/yonder-0003.png
  packages/scroll-component/src/assets/yonder/images/mobile/png/yonder-0004.png
  packages/scroll-component/src/assets/yonder/images/mobile/png/yonder-0005.png
  packages/scroll-component/src/constants/scroll.variant.ts
  packages/scroll-component/src/scroll/scroll.component.scss
  packages/scroll-component/src/scroll/scroll.component.stories.mdx
  packages/scroll-component/src/scroll/scroll.component.ts
  packages/scroll-component/src/shared/globals.d.ts
  packages/scroll-component/src/shared/tailwind.element.ts
  packages/scroll-component/src/shared/tailwind.global.css
  packages/scroll-component/src/types/scroll.component.ts
  packages/scroll-component/src/utils/breakpoints.ts
  packages/scroll-component/src/utils/debounce.ts
  packages/scroll-component/src/utils/getImages.ts
  packages/scroll-component/src/utils/preload.ts
  packages/scroll-component/src/utils/setupCanvas.ts
  packages/scroll-component/src/utils/updateText.ts
  packages/scroll-component/tailwind.config.js
  packages/scroll-component/tsconfig.json
  packages/scroll-component/vite.config.js
  packages/scroll-component/yarn.lock
Labels: feature
